### ISSUE TITLE
mirror -R crashes lftp when there are symlinks

### ISSUE THREAD

**Issue by GenaBitu** [lavv17/lftp#342]
Including log. Replaced all personal info like IP addresses, domains, usernames with placeholders.
[log.txt](https://github.com/lavv17/lftp/files/974623/log.txt)

**Comment by GenaBitu** [comment]
Would be solved by #343, although this shouldn't happen even without that.

**Comment by meta-coder** [comment]
For me, under sftp protocol, instead of updating remote symlinks `mirror -R' initiates a new connection for every symlink it encounters, and produces "status code=4(Failure), message=Failure" errors for each changed symlink.

**Comment by lavv17** [comment]
should be fixed in 128aefc0fb942638263e49f5bdd06504f76fdc87 (released in 4.7.5)

**Comment by GenaBitu** [comment]
No, I am on 4.7.7 (on Debian) and the issue is still present :(

**Comment by lavv17** [comment]
Can you provide a stack trace? Compile using configure --with-debug, run under gdb or valgrind. In gdb type bt after emergency stop.

**Comment by meta-coder** [comment]
Hi author of lftp, thank you for creating and maintaining lftp.
I like lftp and I use it regularly for sftp/ftp/http transfers. The protocol-specific commands are quite lacking and lftp provides a rich common interface to those protocols. Thank you!

**Comment by GenaBitu** [comment]
Unfortunately, I can't seem to compile neither master nor the 4.7-stable branch. I got this:

```
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(float)’:
../lib/math.h:2576:1: error: ‘int signbit(float)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:691:3: note: previous declaration ‘constexpr bool std::signbit(float)’
   signbit(float __x)
   ^~~~~~~
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(double)’:
../lib/math.h:2576:1: error: ‘int signbit(double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:695:3: note: previous declaration ‘constexpr bool std::signbit(double)’
   signbit(double __x)
   ^~~~~~~
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(long double)’:
../lib/math.h:2576:1: error: ‘int signbit(long double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:699:3: note: previous declaration ‘constexpr bool std::signbit(long double)’
   signbit(long double __x)
   ^~~~~~~
Makefile:2203: recipe for target 'ResMgr.lo' failed
make[2]: *** [ResMgr.lo] Error 1
make[2]: Leaving directory '/home/marek995/lftp/src'
Makefile:1604: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/marek995/lftp'
Makefile:1549: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by GenaBitu** [comment]
Seems to me like #273

**Comment by lavv17** [comment]
You can just use last version tarball. It should compile just fine.

пт, 23 июня 2017, 0:25 GenaBitu <notifications@github.com>:

**Comment by GenaBitu** [comment]
More errors, one of which I solved by installing libunistring-dev, but other gives:

```
make  all-recursive
make[1]: Entering directory '/home/marek995/lftp-4.7.7'
Making all in m4
make[2]: Entering directory '/home/marek995/lftp-4.7.7/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/marek995/lftp-4.7.7/m4'
Making all in doc
make[2]: Entering directory '/home/marek995/lftp-4.7.7/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/marek995/lftp-4.7.7/doc'
Making all in lib
make[2]: Entering directory '/home/marek995/lftp-4.7.7/lib'
make  all-recursive
make[3]: Entering directory '/home/marek995/lftp-4.7.7/lib'
make[4]: Entering directory '/home/marek995/lftp-4.7.7/lib'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT dummy.o -MD -MP -MF .deps/dummy.Tpo -c -o dummy.o dummy.c
mv -f .deps/dummy.Tpo .deps/dummy.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT wcwidth.o -MD -MP -MF .deps/wcwidth.Tpo -c -o wcwidth.o wcwidth.c
wcwidth.c: In function ‘wcwidth’:
wcwidth.c:39:14: warning: implicit declaration of function ‘uc_width1’ [-Wimplicit-function-declaration]
       return uc_width1 (wc);
              ^~~~~~~~~
mv -f .deps/wcwidth.Tpo .deps/wcwidth.Po
rm -f libgnu.a
ar cru libgnu.a dummy.o wcwidth.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libgnu.a
make[4]: Leaving directory '/home/marek995/lftp-4.7.7/lib'
make[3]: Leaving directory '/home/marek995/lftp-4.7.7/lib'
make[2]: Leaving directory '/home/marek995/lftp-4.7.7/lib'
Making all in src
make[2]: Entering directory '/home/marek995/lftp-4.7.7/src'
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT PollVec.lo -MD -MP -MF .deps/PollVec.Tpo -c -o PollVec.lo PollVec.cc
mv -f .deps/PollVec.Tpo .deps/PollVec.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT SMTask.lo -MD -MP -MF .deps/SMTask.Tpo -c -o SMTask.lo SMTask.cc
mv -f .deps/SMTask.Tpo .deps/SMTask.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT ProcWait.lo -MD -MP -MF .deps/ProcWait.Tpo -c -o ProcWait.lo ProcWait.cc
mv -f .deps/ProcWait.Tpo .deps/ProcWait.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT GetPass.lo -MD -MP -MF .deps/GetPass.Tpo -c -o GetPass.lo GetPass.cc
mv -f .deps/GetPass.Tpo .deps/GetPass.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT ConnectionSlot.lo -MD -MP -MF .deps/ConnectionSlot.Tpo -c -o ConnectionSlot.lo ConnectionSlot.cc
mv -f .deps/ConnectionSlot.Tpo .deps/ConnectionSlot.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT CharReader.lo -MD -MP -MF .deps/CharReader.Tpo -c -o CharReader.lo CharReader.cc
mv -f .deps/CharReader.Tpo .deps/CharReader.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT Cache.lo -MD -MP -MF .deps/Cache.Tpo -c -o Cache.lo Cache.cc
mv -f .deps/Cache.Tpo .deps/Cache.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT LsCache.lo -MD -MP -MF .deps/LsCache.Tpo -c -o LsCache.lo LsCache.cc
mv -f .deps/LsCache.Tpo .deps/LsCache.Plo
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -g  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -MT FileAccess.lo -MD -MP -MF .deps/FileAccess.Tpo -c -o FileAccess.lo FileAccess.cc
In file included from ascii_ctype.h:26:0,
                 from FileAccess.cc:30:
../lib/c-ctype.h:29:3: error: #error "Please include config.h first."
  #error "Please include config.h first."
   ^~~~~
../lib/c-ctype.h:31:1: error: ‘_GL_INLINE_HEADER_BEGIN’ does not name a type
 _GL_INLINE_HEADER_BEGIN
 ^~~~~~~~~~~~~~~~~~~~~~~
../lib/c-ctype.h:364:1: error: ‘_GL_INLINE_HEADER_END’ does not name a type
 _GL_INLINE_HEADER_END
 ^~~~~~~~~~~~~~~~~~~~~
In file included from FileAccess.cc:30:0:
FileAccess.cc: In member function ‘int FileAccess::device_prefix_len(const char*) const’:
ascii_ctype.h:34:41: error: ‘c_isalnum’ was not declared in this scope
 #define is_ascii_alnum(c)  c_isalnum((c))
                                         ^
FileAccess.cc:421:22: note: in expansion of macro ‘is_ascii_alnum’
    while(path[i] && (is_ascii_alnum(path[i]) || strchr("$_-",path[i])))
                      ^~~~~~~~~~~~~~
Makefile:1065: recipe for target 'FileAccess.lo' failed
make[2]: *** [FileAccess.lo] Error 1
make[2]: Leaving directory '/home/marek995/lftp-4.7.7/src'
Makefile:470: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/marek995/lftp-4.7.7'
Makefile:415: recipe for target 'all' failed
make: *** [all] Error 2
```
